### ISSUE TITLE
Incorrect make call on line 36 of Makefile

### ISSUE THREAD

**Issue by BasementTrix** [cfengine/design-center#463]
Currently, line is:

cd tools/cf-sketch; make install-full PREFIX=$(DESTDIR) GIT=$(GIT)

Should be:

cd tools/cf-sketch; $(MAKE) install-full PREFIX=$(DESTDIR) GIT=$(GIT)

Causes build to fail where 'make' on the $PATH is not GNU make.

Or, in 'git diff' form:

--- a/Makefile
+++ b/Makefile
@@ -33,6 +33,6 @@ install-sketches:
        /bin/cp -rp ./sketches $(DESTDIR)/
 
 install-tools:
-       cd tools/cf-sketch; make install-full PREFIX=$(DESTDIR) GIT=$(GIT)
+       cd tools/cf-sketch; $(MAKE) install-full PREFIX=$(DESTDIR) GIT=$(GIT)
 
 install: install-sketches install-tools

**Comment by tzz** [comment]
@nickanderson YES

**Comment by BasementTrix** [comment]
Line 22:  same problem for target "check"

        cd tools/test; make api_selftest_junit NOIGNORE=1
should be
        cd tools/test; ${MAKE} api_selftest_junit NOIGNORE=1

**Comment by nickanderson** [comment]
It is in master

https://github.com/cfengine/design-center/blob/234baabf3a342815bc59f1c4b7157aa95c6c3d82/Makefile#L22

Did I miss something else?
